### ISSUE TITLE
ValueError in checking refractory and time step compatibility

### ISSUE THREAD

**Issue by srcole** [voytekresearch/fakespikes#3]
2ms is a multiple of 100us, right? But according to python:
`.002 % .0001 = 9.999999999999995e-05`

Resulting in the error:
```
C:\gh\bv\fakespikes\neurons.py in __init__(self, n, t, dt, refractory, seed, private_stdev)
     40             raise ValueError("dt must be less than 0.001 seconds (1 ms)")
     41         if (refractory % dt) != 0:
---> 42             raise ValueError("refractory must be integer multiple of dt")
     43 
     44         self.n = n

ValueError: refractory must be integer multiple of dt
```

So maybe this condition needs to be checked differently to bypass this bug. e.g. 
`int(refractory/dt) == refractory/dt`

**Comment by parenthetical-e** [comment]
This should be addressed by commit 676b6ca5c9377a70e5c6085a0b5b390867d6fb68
