### ISSUE TITLE
Can't increase temporal resolution enough.

### ISSUE THREAD

**Issue by torbenator** [voytekresearch/fakespikes#5]
from fakespikes import neurons, util

dt = 0.001 #works

"""
Doesn't work: 
dt= 0.0001
"""

nNeuB = 50
S = 1
T = 50
nrnsB = neurons.Spikes(nNeuB, T, dt=dt, seed=np.random.randint(10000))

When I make dt smaller, I get:

refractory must be a integer multiple of dt

**Comment by parenthetical-e** [comment]
Fixed in 0b577eec38786316652f740069e041dff6ff4e3c. 

Sorry it took three tries to get this right, T.

**Comment by torbenator** [comment]
yay it worked!

**Comment by parenthetical-e** [comment]
Halifreekingulah

(e)
